export const GET_PARKING_LOTS = "GET_PARKING_LOTS";
export const GET_PARKING_SLOTS = "GET_PARKING_SLOTS";
export const GET_CHARGES = "GET_CHARGES";

export const SET_PARKING_LOTS = "SET_PARKING_LOTS";
export const SET_PARKING_SLOTS = "SET_PARKING_LOTS";
export const SET_CHARGES = "GET_CHARGES";
